name: retro_gaming_app
description: To follow the evolution of your collection whether it is new generation or retro consoles.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2  
  freezed_annotation: ^2.0.4
  graphql_flutter: ^5.1.0
  shared_preferences: ^2.0.8


dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: 2.0.3+1
  json_serializable: ^6.2.0



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
