name: retro_gaming_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2  
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
