on: pull_request
name: CHANGELOG.md
jobs:
  build:
    name: Check changelog update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check changelog has been update
        id: changelogcheck
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main checking changelog..."
          if [ -z "$(git diff --name-only origin/main | grep CHANGELOG.md)" ]; then
            echo "[FAIL] - Changelog has not been updated"
            exit 1
          else
            echo "[SUCCESS] - Changelog has been updated"
          fi