name: Build

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 16.x
      - run: echo $GOOGLE_SERVICES | base64 -d > android/app/google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      - uses: subosito/flutter-action@v2
      - name: Build appbundle
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze .
          flutter test
          flutter build appbundle --debug
  