on: pull_request
name: Git flow is up to date
jobs:
  build:
    name: Check branch up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check up to date
        id: checkuptodate
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main checking if branch is up to date..."
          git fetch
          count=$(git rev-list --count origin/${{ github.head_ref }}..origin/${{ github.base_ref }})
          if [ $count == 0 ]; then
            echo "[SUCCESS] - Your branch is up to date"  
          else
            echo "[FAIL] - your branch is $count commits late. Please rebase."  
            exit 1
          fi