on: 
  workflow_dispatch:
    branches:
      - main
name: App version
jobs:
  build:
    name: Check app version is upgraded
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version is upgraded
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main checking if version is upgraded..."
          git show origin/main:pubspec.yaml >> previous_pubspec.yaml
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2 | cut -d '+' -f1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          PREVIOUS_VERSION=$(more previous_pubspec.yaml | grep version: | cut -d ' ' -f2 | cut -d '+' -f1)
          echo "PREVIOUS_VERSION=$$PREVIOUS_VERSION" >> $GITHUB_OUTPUT
          echo "Upgrade version $PREVIOUS_VERSION to $VERSION"
          if [ $PREVIOUS_VERSION == $VERSION ]; then
            echo "[FAIL] - App version is not upgraded"  
            exit 1
          else
            echo "[SUCCESS] - App version is upgraded"  
          fi
