on:
  push:
    branches:
      - main
name: Deploy Flutter Web Application
jobs:
  build:
    name: Deploy Flutter Web Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: subosito/flutter-action@v2
      - name: Flutter build web
        run: |
          flutter clean
          flutter pub get
          flutter build web